apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hermes
  namespace: xpd-report-agent
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hermes
      app.kubernetes.io/part-of: xpd-report-agent
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: xpd-report-agent
  namespace: xpd-report-agent
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: xpd-report-agent
      app.kubernetes.io/part-of: xpd-report-agent
